name: horus # you probably want to 'snapcraft register <name>'
version: '0.2rc1' # just for humans, typically '1.2+git' or '1.3.2'
summary: horus 3D scanning application
description: |
  Horus is a general solution for 3D laser scanning. It provides
  graphic user interfaces for connection, configuration, control,
  calibration and scanning with Open Source Ciclop 3D Scanner.
grade: devel # must be 'stable' to release into candidate/stable channels
confinement: strict # use 'strict' once you have the right plugs and slots

apps:
  horus:
    command: desktop-launch horus
    plugs:
      - home
      - network
      - x11
      - gsettings
      - opengl
      - raw-usb
      - browser-support
    desktop: usr/share/applications/horus.desktop

parts:
  base:
    plugin: nil
    after:
      - desktop-gtk2

  horus:
    plugin: nil
    stage-packages:
      - horus
      - python-numpy
      - python-wxgtk3.0
      - python-wxversion
    install: |
      set -ex
      (cd $SNAPCRAFT_PART_INSTALL/usr/lib/wx/python;
       ln -s wx3.0.pth wx.pth)
      (cd $SNAPCRAFT_PART_INSTALL/usr/lib/;
       ln -s libblas/libblas.so.3 libblas.so.3)
      (cd $SNAPCRAFT_PART_INSTALL/usr/lib/;
       ln -s lapack/liblapack.so.3 liblapack.so.3)
      (cd $SNAPCRAFT_PART_INSTALL/usr/bin/;
       ln -s ../share/horus res)
    after:
      - base
    organize:
      usr/bin/horus: usr/bin/horus.horus.snap

  local:
    source: ./local
    plugin: dump
    after:
      - horus
    organize:
      horus: usr/bin/horus
